
데이터 핸들링
============================

[목차]
1. 넘파이(NumPy)
2. 판다스(Pandas)

넘파이(NumPy)
-------------
머신러닝의 주요 알고리즘은 선형대수와 통계 등에 기반한다. 특히 선형대수는 수학뿐만 아니라 다른 영역의 자연과학, 공학에서 널리 쓰인다. 이러한 선형대수를 프로그램에서 쉽게 다룰 수 있도록 지원하는 대표적인 패키지가 넘파이(NumPy)이다.

In [ ]:
# 넘파이스 모듈 불러오기
# numpy 전체를 적을 필요 없이 np만으로 numpy 모듈을 사용할 수 있다.

넘파이(NumPy)의 기반의 데이터 타입은 ndarray이다.
- array(리스트): 리스트와 같은 인자를 받아 ndarray로 변환한다.
- shape: ndarray의 크기, 행과 열의 수를 튜플 형태로 가지는 객체 변수 (차원또한 알 수 있다. )
- ndim : ndarray의 차원 정보를 가지는 객체 변수

ndarray1의 타입: <class 'numpy.ndarray'>
ndarray1의 형태: (3,)
ndarray1의 차원: 1
ndarray2의 타입: <class 'numpy.ndarray'>
ndarray2의 형태: (2, 3)
ndarray2의 차원: 2
ndarray3의 타입: <class 'numpy.ndarray'>
ndarray3의 형태: (1, 2, 3)
ndarray3의 차원: 3


ndarray내의 데이터 값은 숫자, 문자, 불(참/거짓) 값 모두 가능하다.<br/>
ndarray의 계산의 특성상 동일한 ndarray내의 값은 모두 데이터 타입을 가진다.<br/>
만약 다른 데이터 타입을 가지는 리스트일 경우 크기가 더 큰 데이터 타입으로 변경된다.
- dtype: ndarray내 값의 데이터 타입을 가지는 객체 변수

[1 2 3] int64
[1. 2. 3.] float64
['1' '2' 'hello'] <U21


메모리를 절약하기 위해 narray내 값의 데이터 타입을 강제로 변경해줘야 할 필요가 있다.
- astype('데이터 타입'): 파라미터로 변경할 데이터 타입을 문자형으로 입력해준다. ndarray내 값을 해당 데이터 타입으로 변경한다.

[1. 2. 3.] float64
[1 2 3] int32


자주 사용되는 형태의 ndarray은 특정 함수를 통해 쉽게 선언할 수 있다.
- arange(정수): 0부터 (입력받은 정수-1)까지 순차적으로 구성된 ndarray를 반환한다.
- arange(start=정수, stop=정수): start부터 (stop-1)까지 순차적으로 구성된 ndarray를 반환한다.
- zeros(정수): 0부터 (입력받은 정수-1)까지 0으로 구성된 ndarray를 반환한다.
- ones(정수): 0부터 (입력받은 정수-1)까지 1로 구성된 ndarray를 반환한다.
 <br/>
**arange()로 생성된 ndarray내 값의 데이터 타입은 int64** <br/>
**zeros(), ones()로 생성된 ndarray내 값의 데이터 타임은 float64**

arange(10):  [0 1 2 3 4 5 6 7 8 9] int64
arange(10):  [1 2 3 4 5 6 7 8 9] int64
zeros(10):  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
ones(1):  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


ndarray의 차원과 크기를 변경해야할 필요가 있다. reshape() 메소드를 통해 해당 작업을 수행 할 수 있다.
- reshape(리스트): ndarray를 입력받은 shape으로 변경한다. -1을 파라미터로 입력하면 다른 파라미터와 호환되는 shape으로 변경한다.

**만약 입력받은 shape으로 변경하지 못할 경우 에러가 발생한다.**

1차원 ndarray (12,): 
[ 0  1  2  3  4  5  6  7  8  9 10 11] 

2차원 ndarray (2, 6): 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

3차원 ndarray (2, 2, 3): 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 

-1을 파라미터로 입력 : 
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


ndarray내 값에 접근하기 위해서는 리스트와 유사하게 대괄호([]) 안에 인덱스를 넣으면 된다.<br/>
list와 마찬가지로 특정 값에 접근하여 변경할 수 있다.

[1 2 3 4 5 6 7 8 9]
4 

[ 1  2  3  4  5 20  7  8  9]


ndarray내 특정 값을 세트롤 추출하는 방법은 다음과 같다.
- 특정 인덱스를 통한 추출: 대괄호([]) 안에 인덱스를 넣어 값을 추출한다.
- 슬라이싱(slicing): 연속된 인덱스상의 값을 ndarray로 추출한다. ':' 앞뒤에 시작 인덱스 종료 인덱스를 입력한다. 만약 적지 않으면 해당 방향으로 끝까지 ndarray로 추출한다.
- 팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트로 지정해 ndarray로 추출한다.
- 불린 인덱싱(Boolean Indexing): 조건식을 만족하는 값을 ndarray로 추출한다.

In [ ]:

# [행(row), 열(col)]
# 특정 인덱스를 통한 추출

# 슬라이싱(slicing)


# 팬시 인덱싱(Fancy Indexing)


# 불린 인덱싱(Boolean Indexing)


특정 인덱스를 통한 추출
6 

슬라이싱(slicing)
[4 5 6]
-----------------
[3 6]
-----------------
[5 6]
-----------------
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

팬시 인덱싱(Fancy Indexing)
[3 6]
-----------------
[[1 2]
 [4 5]]
불린 인덱싱(Boolean Indexing)
[6 7 8 9]


행렬을 정렬하는 방법은 두가지가 존재한다.
- numpy.sort(<ndarray>): 함수로 파라미터로 입력된 ndarray가 정렬된 값을 반환한다. **원본은 그대로 유지된다.**
- ndarray.sort(): 메소드로 원본을 정렬한다. 반환값이 없다(None). **원본이 유지되지 않는다.**

numpy.sort()로 정렬
원본:  [4 1 8 6]
함수로 정렬:  [1 4 6 8] 

ndarray.sort()로 정렬
원본:  [1 4 6 8]
함수로 정렬:  None


정렬된 행렬의 값들의 원본 인덱스가 필요한 경우가 있다. arsort()함수를 통해 해당 작업을 수행할 수 있다.
- argsort(): 행렬 정렬 시 원본 행렬의 인덱스를 ndarray로 반환한다.

원본:  [4 1 8 6]
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


판다스(Pandas)
--------------
판다스(Pandas)는 행과 열로 이뤄진 2차원 데이터를 효율적으로 처리할 수 있는 기능을 제공한다. 앞선 넘파이(NumPy)보다 쉬운 데이터 핸들링을 제공하기에 데이터 처리 목적으로 주로 사용한다.

In [ ]:
# 판다스(Pandas) 모듈 불러오기


# 구글드라이브 연동


Mounted at /content/drive


판다스(Pandas)는 다양한 형태의 데이터를 DataFrame으로 불러와 데이터를 처리한다.
- read_csv('경로'): 입력된 경로의 csv를 DataFrame으로 불러와 반환한다.
- shape: DataFrame의 객체변수로 DataFrame의 행과 열의 크기를 튜플로 반환한다.
- info(): DataFrame의 메소드로 DataFrame의 총 데이터 건수와 데이터 타입, Null 건수를 반환한다.
- Describe(): DataFrame의 메소드로 DataFrame의 칼럼별 숫자형 데이터값의 분포도, 평균값, 최댓값, 최솟값을 반환한다.

In [ ]:
# csv 파일 불러오기
# 앞의 다섯 행만 출력

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
# DataFrame의 행과 열의 크기


(891, 12)

In [ ]:
# DataFrame의 데이터 정보


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
# DataFrame의 숫자형 데이터 분석
''' count: Not Null의 데이터 수
    mean: 전체 데이터의 평균값
    std: 표준편차
    min: 최솟값
    max: 최댓값
    25%: 전체 데이터에서 25%에 위치한 값
    50%: 전체 데이터에서 25%에 위치한 값
    75%: 전체 데이터에서 25%에 위치한 값'''



PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

DataFrame의 []에 컬럼명을 입력하면 해당 컬럼을 Series로 반환한다.

<class 'pandas.core.series.Series'>


0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

DataFrame과 ndarray, 리스트, 딕셔너리는 서로 변환할 수 있다.

<class 'list'> to <class 'pandas.core.frame.DataFrame'>


col1  col2  col3
0     1     2     3
1     4     5     6

In [ ]:
# ndarray to DataFrame


<class 'numpy.ndarray'> to <class 'pandas.core.frame.DataFrame'>


col1  col2  col3
0     1     2     3
1     4     5     6

In [ ]:
# 딕셔너리 to DataFrame


# 딕셔너리의 key 값이 컬럼명이 된다.


<class 'dict'> to <class 'pandas.core.frame.DataFrame'>


col1  col2  col3
0     1     2     3
1     4     5     6

많은 머신러닝 패키지가 넘파이(NumPy)를 지원하기에 주로 DataFrame을 ndarray로 변환한다.

In [ ]:
# DataFrame to ndarray


<class 'pandas.core.frame.DataFrame'> to <class 'numpy.ndarray'>
ndarray의 shape:  (2, 3)
[[1 2 3]
 [4 5 6]]


DataFrame을 리스트로 변환하기 위해서는 먼저 DataFrame을 ndarray로 변환한 다음 리스트로 변환하면 된다.
- tolist(): ndarray를 리스트로 변환하는 메소드

In [ ]:
# DataFrame to 리스트


<class 'pandas.core.frame.DataFrame'> to <class 'list'>


[[1, 2, 3], [4, 5, 6]]

- to_dict(): DataFrame을 딕셔너리로 반환하는 DataFrame의 메소드

In [ ]:
# DataFrame to 딕셔너리


<class 'pandas.core.frame.DataFrame'> to <class 'dict'>


{'col1': {0: 1, 1: 4}, 'col2': {0: 2, 1: 5}, 'col3': {0: 3, 1: 6}}

DataFrame에 칼럼을 새로 추가하거나 수정하기 위해서는 [] 사이에 새로운 칼럼명을 입력하면된다.

In [ ]:
# 상수값을 할당하면 모든 값이 해당 상수값으로 입력된다.


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  ch_Age  
0      0         A/5 21171   7.2500   NaN        S       0  
1      0          PC 17599  71.2833   C85        C       0  
2      0  STON/O2. 3101282   7.9250   NaN        S       0  
3      0            113803  53.1000  C123        S       0  
4      0            373450   8.0500   NaN        S       0

In [ ]:
# 다른 컬럼을 할당하면 같은 인덱스의 값이 입력된다.


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  ch_Age  
0      0         A/5 21171   7.2500   NaN        S   220.0  
1      0          PC 17599  71.2833   C85        C   380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S   260.0  
3      0            113803  53.1000  C123        S   350.0  
4      0            373450   8.0500   NaN        S   350.0

DataFrame의 데이터를 삭제할 때는 drop() 메소드를 사용한다.
- drop(labels:<문자형> = None, axis:<숫자형> = 0, index:<숫자형> = None, inplace:<불린> = False): <br/>
 axis에 0을 입력하면 행을 제거하고 1을 입력하면 열을 제거한다.<br/>
axis의 값에 따라 같이 입력된 값을 인덱스인지 컬럼명인지 판단한다.<br/>
inplace가 False면 변경된 새로운 DataFrame을 반환하고 True면 원본 데이터를 변경한다.

In [ ]:
# 첫번째 행 삭제


PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  ch_Age  
1      0          PC 17599  71.2833   C85        C   380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S   260.0  
3      0            113803  53.1000  C123        S   350.0  
4      0            373450   8.0500   NaN        S   350.0  
5      0            330877   8.4583   NaN        Q     NaN

In [ ]:
# 원본은 그대로 유지

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  ch_Age  
0      0         A/5 21171   7.2500   NaN        S   220.0  
1      0          PC 17599  71.2833   C85        C   380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S   260.0  
3      0            113803  53.1000  C123        S   350.0  
4      0            373450   8.0500   NaN        S   350.0

In [ ]:
# 'ch_Age' 열 제거

# 반환값 없음

<class 'NoneType'>


In [ ]:
titanic_df.head() # 원본 데이터 변경

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

DataFrame에서 데이터 세트를 선택하거나 필터링할 때 다음과 같은 방법을 사용한다.
- [ ]: [ ] 안에 컬럼명, 슬라이싱, 불린 인덱싱을 입력하여 데이터를 선택 및 필터링한다.
- iloc[]: 칼럼 위치에 기반하여 데이터를 선택 및 필터링한다.
- loc[]: 컬럼 명에 긴반하여 데이터를 선택 및 필터링한다. 불린 인덱싱 또한 가능하다.

In [ ]:
#1 [] 사용
# 컬럼 명으로 데이터 선택


0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [ ]:
# 슬라이싱으로 데이터 선택
# 시작 부터 (끝-1) 까지

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [ ]:
# 불린 인덱싱으로 데이터 선택


PassengerId  Survived  Pclass                                      Name  \
6             7         0       1                   McCarthy, Mr. Timothy J   
11           12         1       1                  Bonnell, Miss. Elizabeth   
15           16         1       2          Hewlett, Mrs. (Mary D Kingcome)    
33           34         0       2                     Wheadon, Mr. Edward H   
52           53         1       1  Harper, Mrs. Henry Sleeper (Myna Haxtun)   

       Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
6     male  54.0      0      0       17463  51.8625   E46        S  
11  female  58.0      0      0      113783  26.5500  C103        S  
15  female  55.0      0      0      248706  16.0000   NaN        S  
33    male  66.0      0      0  C.A. 24579  10.5000   NaN        S  
52  female  49.0      1      0    PC 17572  76.7292   D33        C

In [ ]:
#2 iloc[] 사용


'Braund, Mr. Owen Harris'

In [ ]:
# 첫 번째 행 삭제
# 변경된 DataFrame에서 첫번째 행 데이터 추

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [ ]:
#슬라이싱 가능

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name  
0                            Braund, Mr. Owen Harris  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...

In [ ]:
#3 loc[] 사용


'Braund, Mr. Owen Harris'

In [ ]:
# 첫 번째 행 삭제
# 변경된 DataFrame에서 첫번째 행 데이터 추출
# ch_df.loc[0, 3] 에러 발생, 인덱스 0행이 삭제됨


'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [ ]:
# 불린 인덱스 가능

PassengerId  Survived  Pclass                                      Name  \
6             7         0       1                   McCarthy, Mr. Timothy J   
11           12         1       1                  Bonnell, Miss. Elizabeth   
15           16         1       2          Hewlett, Mrs. (Mary D Kingcome)    
33           34         0       2                     Wheadon, Mr. Edward H   
52           53         1       1  Harper, Mrs. Henry Sleeper (Myna Haxtun)   

       Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
6     male  54.0      0      0       17463  51.8625   E46        S  
11  female  58.0      0      0      113783  26.5500  C103        S  
15  female  55.0      0      0      248706  16.0000   NaN        S  
33    male  66.0      0      0  C.A. 24579  10.5000   NaN        S  
52  female  49.0      1      0    PC 17572  76.7292   D33        C

In [ ]:
# 여러 조건을 적용할 수 있다.
''' &: AND
    |: OR
    ~: NOT '''
# 개별 조건은 ()로 묶어야 한다.

# 나이는 60세 이상, 1등급 승객 추출


PassengerId  Survived  Pclass                               Name     Sex  \
54            55         0       1     Ostby, Mr. Engelhart Cornelius    male   
96            97         0       1          Goldschmidt, Mr. George B    male   
170          171         0       1          Van der hoef, Mr. Wyckoff    male   
252          253         0       1          Stead, Mr. William Thomas    male   
275          276         1       1  Andrews, Miss. Kornelia Theodosia  female   

      Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
54   65.0      0      1    113509  61.9792   B30        C  
96   71.0      0      0  PC 17754  34.6542    A5        C  
170  61.0      0      0    111240  33.5000   B19        S  
252  62.0      0      0    113514  26.5500   C87        S  
275  63.0      1      0     13502  77.9583    D7        S

DataFrame과 Series를 정렬할 때는 sort_values() 메소드를 이용한다.
- sort_values(by:<문자형>=None, ascending:<불린>=True, inplace:<불린>=False) : <br/> by에는 정렬하고자 하는 컬럼명을 입력한다. <br/>
ascending이 True면 오름차순, False면 내림차순으로 정렬한다. <br/>
inplace가 True면 원본을 변경하고, False면 정렬된 DataFrame 또는 Series를 반환한다.

PassengerId  Survived  Pclass                                   Name  \
845          846         0       3                    Abbing, Mr. Anthony   
746          747         0       3            Abbott, Mr. Rossmore Edward   
279          280         1       3       Abbott, Mrs. Stanton (Rosa Hunt)   
308          309         0       2                    Abelson, Mr. Samuel   
874          875         1       2  Abelson, Mrs. Samuel (Hannah Wizosky)   

        Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked  
845    male  42.0      0      0  C.A. 5547   7.55   NaN        S  
746    male  16.0      1      1  C.A. 2673  20.25   NaN        S  
279  female  35.0      1      1  C.A. 2673  20.25   NaN        S  
308    male  30.0      1      0  P/PP 3381  24.00   NaN        C  
874  female  28.0      1      0  P/PP 3381  24.00   NaN        C

PassengerId  Survived  Pclass                             Name   Sex  \
868          869         0       3      van Melkebeke, Mr. Philemon  male   
153          154         0       3  van Billiard, Mr. Austin Blyler  male   
361          362         0       2        del Carlo, Mr. Sebastiano  male   
282          283         0       3        de Pelsmaeker, Mr. Alfons  male   
286          287         1       3          de Mulder, Mr. Theodore  male   

      Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
868   NaN      0      0         345777   9.5000   NaN        S  
153  40.5      0      2       A/5. 851  14.5000   NaN        S  
361  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C  
282  16.0      0      0         345778   9.5000   NaN        S  
286  30.0      0      0         345774   9.5000   NaN        S

DateFrame에서 사용 가능한 집합(Aggregation) 메소드는 다음과 같다.
- count(): 해당 열의 데이터 수를 센다.
- sum(): 해당 열의 모든 데이터의 합을 구한다.
- max(): 해당 열 내의 최댓값을 구한다.
- min(): 해당 열 내의 최솟값을 구한다.

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

Age     29.699118
Fare    32.204208
dtype: float64

각 컬럼을 기준으로 데이터를 분석할 필요가 있다. 그럴경우 groupby()메소드를 이용한다.
- groupby(by:<문자형>=None): by에 새로운 기준이 될 컬럼명을 입력한다.

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216   
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491

In [ ]:
# 그룹화한 DataFrame에서도 DataFrame/Series를 추출할 수 있다.


Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

그룹화한 DataFrame에서 추출된 DataFrame/Seies에 여러 집합(aggregation) 메소드를 사용할 수 있다.
- agg(리스트/딕셔너리) : 입력된 리스트/딕셔너리 안에 사용할 집합 메소드를 입력하면 된다.

In [ ]:
# agg() 메소드를 통해 여러 집합(aggregation) 메소드를 사용할 수 있다.


max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [ ]:
# 딕셔너리 생성


Age  SibSp      Fare
Pclass                            
1       38.233441     90  512.3292
2       29.877630     74   73.5000
3       25.140620    302   69.5500

데이터 중에 없는 데이터가 있다. DataFrame에서 해당 데이터는 NaN으로 표시된다. 머신러닝 알고리즘에서는 해당 데이터를 처리하지 않기에 다른 값을 채워넣어 줘야한다.
- isna(): 데이터가 NaN인지 아닌지 알려준다.
- fillna(대체할 값, inplace:<불린>=False): NaN 데이터를 입력된 값으로 대체한다. <br/> inplace가 False면 NaN을 채운 DataFrame을 새로 반환한다. True면 원본에 바로 채운다.

In [ ]:
# NaN이면 True, 아니면 False를 반환한다.


PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   
3        False     False   False  False  False  False  False  False   False   
4        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False  
3  False  False     False  
4  False   True     False

In [ ]:
# True는 1, False는 0으로 대응되기에 sum을 통해 NaN데이터 수를 구할 수 있다.


PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# NaN데이터 채우기


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  C000        S

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500  C000        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250  C000        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500  C000        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000  C000        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500  C000        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500  C000        Q  

[891 rows x 12 columns]